---
#
#     Copyright 2018,2017 Red Hat, Inc
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#

- name: search for insights-client
  package_facts:
    manager: rpm
  register: rpm_res
  
- name: delete redaction files
  file:
    state: absent
    dest: "{{ item }}"
  loop:
  - /etc/insights-client/file-redaction.yaml
  - /etc/insights-client/file-content-redaction.yaml
  when: rpm_res.ansible_facts.packages['insights-client'] | length > 0
  
- block:  
  - name: remove weird file permissions
    file:
      attr: -a
      dest: /etc/yum.repos.d/redhat.repo
  
  - yum:
      name:       insights-client
      enablerepo: "{{ temp_insights_repoid }}"
      state:      present

  - yum:
      disablerepo: "{{ temp_insights_repoid }}"    
  when: rpm_res.ansible_facts.packages['insights-client'] | length == 0
